### ISSUE TITLE
For a block of tab-separated text, tabs themselves should not be treated as columns

### ISSUE THREAD

**Issue by fqf2009** [randy3k/AlignTab#41]
e.g. I have a block of tab-separated text, 3 columns, 2 tabs in between. I need to use the following reg expr to make 3 columns to left, center and right align:
(?:\t)/l1l2c3l4r5
So, l1, c3 and r5 works for 3 columns. The l2 and l4 is the redundant.

**Comment by randy3k** [comment]
You may want to consider `\t+`

**Comment by randy3k** [comment]
Did it fix your problem?

**Comment by fqf2009** [comment]
Thanks for the great tool and quick responses. The \t+ expression doesn't
solve my problem, because I only have one tab between two columns. I guess
the program treat tab as one column when it deal with the alignment
settings.

**Comment by randy3k** [comment]
Oh, I didn't read your problem careful enough. You are correct, the separators are also treated as columns. It is one of the features and it will be useful for some cases.

**Comment by randy3k** [comment]
Because it is not bug, I am going to close it.
