### ISSUE TITLE
Add my custom pattern to context drop-down

### ISSUE THREAD

**Issue by akost** [randy3k/AlignTab#43]
Thank you for nice plugin!

I want to add my custom pattern to the default context menu.
![Context menu](https://raw.githubusercontent.com/randy3k/AlignTab/fig/alignby.png)

Is it possible to do (simple way)?

I did it on my old Sublime Text 2 installation, but I can't remeber how it was done.

Thanks!

**Comment by randy3k** [comment]
I recommend you update to ST3 and to add an item to the context menu, follow the instruction in the README.md.

**Comment by akost** [comment]
Thanks.
Done it already, it works.

Is it possible to move custom item to the top of the list?

**Comment by randy3k** [comment]
Glad to know you did it.

That is not possible without editing the source files. You can do it by cloning this repo to your computer.

**Comment by randy3k** [comment]
should I close it?

**Comment by akost** [comment]
Yes.

Thank you!
