### ISSUE TITLE
Ability to skip a column in the options

### ISSUE THREAD

**Issue by boblauer** [randy3k/AlignTab#44]
I have code that looks like this:

```js
var fs = require('fs')
  , async = require('async')
  ;
```

I want to leave the left side column of the `=` alone, but align the `=`.  So:

```js
var fs    = require('fs')
  , async = require('async')
  ;
```

I don't want to left-align the 1st column, because that pushes `, async` all the way to the left.  Nor do I want to center or right align the first column. I want it to remain untouched, except for the `=` being aligned with the rest.

Is this currently possible?

**Comment by randy3k** [comment]
It is just an regex exercise.
try `(?:var|^\s*,|^\s*;|=)/lrf2`

**Comment by boblauer** [comment]
Thank you so much, you just saved me a ton of time.  Awesome plugin!

**Comment by randy3k** [comment]
I have just added a new flag `u` standing for "unjustified". For now, we can use `=/ull`.
