### ISSUE TITLE
Ignore :aftter and other pseudo-elements

### ISSUE THREAD

**Issue by marcosfreitas** [randy3k/AlignTab#45]
When I was aligning my CSS, I realized that in styles applied to the **:after, :before** and other **pseudo-elements** the plugin also aligned the **colon** of these elements. This affects the style.

When will I align some of the code I did not select him, I just put the pointer inside the CSS block and use my key bindings:
```
[
  {
    "keys": ["ctrl+shift+a"], "command": "align_tab",
    "args" : {"user_input" : ":/f"}
   }
]
```
**I'm using Windows 7 and with the context menu is the same.**
Below is an example of the problem:
![align-tab](https://cloud.githubusercontent.com/assets/1065688/6176305/7d850758-b2dc-11e4-8da8-70f69d2bd3fd.PNG)

**Comment by randy3k** [comment]
You can highlight whatever you want to align and then apply aligntab to the selection.

If no selection is made, aligntab will detect the region automatically.

**Comment by marcosfreitas** [comment]
I know, sometimes it becomes boring. Especially when someone wants to align a css that has been completely produced.

**Comment by tylermumford** [comment]
I was able to use a colon and trailing space (`: `) as the RegEx to exclude pseudo-elements.
