### ISSUE TITLE
Add option to ignore comments when aligning

### ISSUE THREAD

**Issue by zx8** [randy3k/AlignTab#46]
Currently when selecting blocks of texts and hitting my AlignTab keybind, if there are any comments, they get aligned along with the actual code.

It'd be great to add an option to "ignore comments" intelligently (e.g. // or # etc. depending on the language) when aligning.

Thanks
##

**Comment by randy3k** [comment]
it seems a good idea, but i don't want to complicate the already complicated input...any suggestions?

**Comment by zx8** [comment]
Hm, well, so currently the default settings are:

```
{
  "named_patterns": {
    "first_equal" : "=/f",
    "first_comma" : ",/f",
    "first_colon" : ":/f",
    "all_and"     : "&",
    "all_bar"     : "\\|",
    "all_space"   : "\\s*/l1l0"
  }
}
```

Perhaps introduce a new config ```ignored_patterns``` which take precedence over all other patterns, and can be configured by language, then leave it up to the users to configure what they want to ignore (e.g. if they want to ignore things that aren't comments, but should never be aligned?). Something like this:

```
{

  ...

  "ignored_patterns" {
    // Global - applied to all languages
    "*" : [
      "^Do not align me$",
      "^This should(n't| not) be aligned!$",
    ],
    // Python - applied to Python only
    "Python" : [
      "^\s*#.+$"
    ],
    // Perl - applied to Perl only
    "Perl" : [
      "^\s*//.+$
    ]
  }
}
```

Not quite sure how to approach "multiline ignores" though? Perhaps a separate configuration, or merged into "ignored_patterns":
```
"ignored_patterns_multiline" {
    "Python" : [
      "^\s*'''(.+)'''\s*$"
    ],
  }
```

Thoughts?

**Comment by zx8** [comment]
The above approach is also a potential solution for https://github.com/randy3k/AlignTab/issues/45, i.e. one could specify an "ignore pattern" for ```after:``` and ```before:``` when language=CSS

**Comment by randy3k** [comment]
i will give it a thought.

**Comment by zx8** [comment]
Hey Randy - any thoughts yet?

**Comment by randy3k** [comment]
I gauss your suggestion does make sense. But  I will be very busy in the following 2 months and I am afraid that I won't have time to implement it in a short time. A pull request is appreciated.

**Comment by zx8** [comment]
Hey Randy -- I'd really like to help but I'm also very busy lately.

Still very interested in this feature if anyone else is reading this and fancies putting together a PR.

I'm happy to help test/code review. I just don't have the time to put it together from scratch myself.
