### ISSUE TITLE
Support => alignment

### ISSUE THREAD

**Issue by dantman** [randy3k/AlignTab#47]
Ruby, Puppet, and a few other languages use `=>` for some parts of their syntax. Being able to align these would be nice.

You can try to align by `=` but then AlignTab turns them all into `= >`'s.

**Comment by randy3k** [comment]
I believe that you can use `=>` as the input in AlignTab.

**Comment by dantman** [comment]
I'm referring to the context menu -> `Align By` items.

`=>` alignment is more common than some of the other items on the list, but it's not included.

**Comment by randy3k** [comment]
You could add your own items to the context menu, check README.

**Comment by dantman** [comment]
As I said, `=>` is more common than some of the other items in the list.

I think it deserves an entry in that list that exists by default.

**Comment by randy3k** [comment]
I see. How could I call this operator?

**Comment by dantman** [comment]
What, are you asking where `=>` would be used?

It's used in PHP for array syntax:
```php
$arr = array(
  'foo'   => 1,
  'bar'   => 2,
  'baz'   => 3,
  'hello' => 'world',
);
```

It's used in Ruby for hash syntax:
```ruby
h = {
  :foo    => 1,
  :bar    => 2,
  :baz    => 3,
  'Hello' => 'World'
}
```

It's used in Puppet:
```puppet
file { '/home/foo/bar':
  content => "Hello World\n",
  owner   => foo,
  group   => foo,
  mode    => '0644',
}
```

I believe Perl also uses it for hashes:
```perl
%h = (
  foo   => 1,
  bar   => 2,
  baz   => 3,
  hello => "world",
);
```

**Comment by zx8** [comment]
@randy3k - http://en.wikipedia.org/wiki/Fat_comma

**Comment by isimmons** [comment]
Asking what to call it in the menu? "Fat Arrow" seems the best choice IMHO

**Comment by leem32** [comment]
To add align by => to the context menu, go to Preferences -> Package Settings -> AlignTab -> Context Menu and paste this: 
[
   {"caption" : "-"},
    {
      "id": "aligntab",
      "caption": "Align By",
      "children": [
          {
          "caption" : "Array Value ( => )",
          "command" : "align_tab",
          "args"    : {"user_input" : "\\=>"}
          }
      ]
  }
]
Name it whatever you like. I named it "Array Value" because i use it with PHP, so it makes the most sense to me.
When you use => to align make sure the cursor is selected inside the array, or it won't work.

**Comment by randy3k** [comment]
Sorry for the long delay, ede864803f82d4cb8581746404d7bc8c7962a341 adds Fat Arrow and removes some of the un-commons (I think).
