### ISSUE TITLE
Allignment of table with both negative and positive numbers

### ISSUE THREAD

**Issue by AllanLRH** [randy3k/AlignTab#49]
This is a snippet of a LaTeX table I aligned with AlignTab.

```
  &  -1.5    \\
  &  -1.0    \\
  &  -0.5    \\
  &  0.0    \\
  &  0.5    \\
```

While it's beautiful, I'd like to be able to align it like this instead (aligning to the first number, not it's sign).

```
  &  -1.5    \\
  &  -1.0    \\
  &  -0.5    \\
  &   0.0    \\
  &   0.5    \\
```
Is this possible? I can't seem to figure out an appropriate combination of regex and alignment specification.

**Comment by randy3k** [comment]
thought it looks a bit complicated, it is the input that you need
(?<!\\)&|\\\\|[0-9.]*/l0l1

**Comment by randy3k** [comment]
does it work?

**Comment by AllanLRH** [comment]
Yes, sorry for not answering – It's exam time for me :)

It works. However I ran into trouble, when commands are included:
```
foo  &  \num{2.8110e-08}   &  -0.16246           \\
bar  &  \textbf{-123.321}  &  0.16246            \\
```
…but I guess that the point of ignoring the sign when aligning diminishes as the table fills up with commands.
