### ISSUE TITLE
Parenthesizing user input pattern creates extra operators when aligning

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [randy3k/AlignTab#53]
Hi :)

I may be retarded here, but I'm adding a keyboard shortcut to do some basic alignment. Right now, just for the first = or :. That is, 

    {
        "keys" : ["super+<"], "command": "align_tab",
        "args" : {"user_input" : "(:|=)/f"},
        "context":[
            { "key": "selector", "operator": "equal", "operand": "source.js" }
        ]
    }

This will align by these operators, but it'll also add a space and a copy of the operator being aligned, e.g.:

    var os       = = require('os');
    var hostname = = '__NO_SUCH_CUSTOM__';

Without the parentheses (and the /f) there's no adding of operators (but I can't use /f without the parentheses)... Am I just being retarded here or is that a bug?

**Comment by randy3k** [comment]
You should use non-capturing parentheses `(?:regex)`. In your case, it should be `(?::|=)/f`
