### ISSUE TITLE
Can't install via package control

### ISSUE THREAD

**Issue by kambanwait** [randy3k/AlignTab#55]
not sure if I'm being really stupid here but I can't find this via Package Control in ST3. 
![screen shot 2015-11-20 at 09 33 05](https://cloud.githubusercontent.com/assets/951731/11296449/192b925c-8f6a-11e5-9472-470a5e0cf984.png)
##

**Comment by mosinandrey** [comment]
Me to, there is no such package in Package Control for ST3.

**Comment by randy3k** [comment]
I doubt we have already installed it...

**Comment by kambanwait** [comment]
I've got both ST 2 & 3 installed - I wonder if they're interfering in any way? I've got it installed for ST2 but not 3.

**Comment by randy3k** [comment]
Could you try "List Packages" and "Remove Package"?

**Comment by mIcHyAmRaNe** [comment]
can't find it too, 
looked it in "list packages" & "remove package" and in "install packages" but nothing

probably due to this error: "Missing" 
![selection_005](https://user-images.githubusercontent.com/17873513/36624035-b96d15e8-190a-11e8-97e5-d419cebbdb04.png)

**Comment by randy3k** [comment]
I believe it is an issue of package control. You may want to try again later or install AlignTab manually.

**Comment by t3hk0d3** [comment]
@randy3k looks like this is issue of AlignTab specifically. Other packages works fine.

**Comment by randy3k** [comment]
The issue of package control should have been fixed.

**Comment by mIcHyAmRaNe** [comment]
what was the problem?

**Comment by randy3k** [comment]
It was because GitHub changed their TLS requirement to 1.2. 

Did you encounter any issues now?

**Comment by mIcHyAmRaNe** [comment]
it's working, we can find it and install it using package control in sublime text 
and the error message that I mentioned above is gone. 🙂
