### ISSUE TITLE
and How to go back to the default settings of sublime plz?

### ISSUE THREAD

**Issue by Fadeoc** [randy3k/AlignTab#56]
I use less, and all messed up with a aligning by :, so how could I go back to the sublime default aligning plz?

**Comment by randy3k** [comment]
I am not sure what you meant...Could you just undo the changes?

**Comment by Fadeoc** [comment]
rgr, right. was thinking it was a alignment theme or sth.
Thnx.

**Comment by randy3k** [comment]
Still not understand....any, I am closing it now.
