### ISSUE TITLE
Aligning adds space before character - can it be disabled?

### ISSUE THREAD

**Issue by coladarci** [randy3k/AlignTab#61]
```
{
  a: 'b',
  ccc: 'd'
}
```
becomes
```
{
  a   : 'b',
  ccc : 'd'
}
```
when we'd ideally like the semi's to stay right after the keys:
```
{
  a  : 'b',
  ccc: 'd'
}
```
Is this configurable, by any chance? Or Eslint settings would prefer we don't have that extra space..

**Comment by randy3k** [comment]
You can use the `AlignTab` command with input `:/l0l1`.

**Comment by coladarci** [comment]
You, sir, are a class act. (shout out to Maine, too - I'm from Bangor..)

**Comment by randy3k** [comment]
And I used to be in California :).

**Comment by coladarci** [comment]
One more question - can that `:/l0l1.` be adjusted to only match the first instance? I was previously using `:/f`

**Comment by randy3k** [comment]
You could use `:/l0l1f`
