### ISSUE TITLE
Vintage Mode

### ISSUE THREAD

**Issue by ToxaKniotee** [randy3k/AlignTab#62]
In Sublime we use the <kbd>ESC</kbd> key to go into Vintage Mode (VI).

Apparently the <kbd>ESC</kbd> key also stop the table mode, so every time I go into VI mode I have to re enter the regular expressions to be again in table mode.

Is there a way to avoid exiting Table Mode while entering VI mode?
##

**Comment by randy3k** [comment]
I personally do not use Vintage mode, but I think it could be solved by re-defined the keybinds. Say, in your personal keybind file, put the VI <kbd>ESC</kbd> keybind before AlignTab <kbd>ESC</kbd> keybind.

**Comment by randy3k** [comment]
I forgot to mention that you could bind a keybind to the command `align_tab_clear_mode` or 
use the newly added command `AlignTab: Exit Table Mode`.
