### ISSUE TITLE
Align text by end of pattern.

### ISSUE THREAD

**Issue by AndrewAndreev** [randy3k/AlignTab#64]
Hello. It's very cool and powerful package.
But I can't figure out how to align this code:
```
int a;
char *b;
char **c;
```
By this way:
```
int    a;
char  *b;
char **c;
```
In ordinary case it will match in `\**\w;` regexp, but it will form this code:
```
int  a;
char *b;
char **c;
```

So, is it possible? If it is not I would suggest this as feature requiest.
Option to align text by end of patterns instead of start.

**Comment by randy3k** [comment]
` \**\w/lr0` should work.

**Comment by AndrewAndreev** [comment]
@randy3k definitely it works, thanks!
But what is `/lr` ? Is there any documentation on this kind of regexp?

**Comment by randy3k** [comment]
Check [this](https://github.com/randy3k/AlignTab#for-more-complicated-usage-welcome-to-the-regex-world) part of the documentation.

**Comment by AndrewAndreev** [comment]
I've got it, thanks!
