### ISSUE TITLE
Brackets "(", ")", ");"

### ISSUE THREAD

**Issue by Max-Enrik** [randy3k/AlignTab#66]
Hi,

first of all thanks for this great stuff.
How can I add this symbols Brackets "**(** ",  "**)**",  "**);**" ?

If I hear from you soon, that will be better, and thanks.

**Comment by randy3k** [comment]
Could you provide an example? I don't understand what you meant.

**Comment by Max-Enrik** [comment]
Sorry for the initial comment, because I has been seen wrong text at the there and I clean it up.
So, I tried like below code for '(' (bracket).

`
[
   {"caption" : "-"},
    {
      "id": "aligntab",
      "caption": "Align By",
      "children": [
          {
          "caption" : "(",
          "command" : "align_tab",
          "args"    : {"user_input" : "\\("}
          }
      ]
  }
]
`

**Comment by randy3k** [comment]
Did you put it in `Context.sublime-menu`?

**Comment by Max-Enrik** [comment]
Yeah!

![aligntab-scr-01](https://cloud.githubusercontent.com/assets/3518174/20171619/f7558a1c-a74a-11e6-8087-bd1a4b9758ff.jpg)

Does below code correct?
`"args" : {"user_input" : "\\("}`

![aligntab-scr-02](https://cloud.githubusercontent.com/assets/3518174/20171727/75635b78-a74b-11e6-8887-fdde1e604af3.jpg)

**Comment by randy3k** [comment]
Yes, it looks right to me.

**Comment by Max-Enrik** [comment]
Sounds good, but it does not work for me, so what can I for it?

**Comment by randy3k** [comment]
Could you see the menu item?

**Comment by Max-Enrik** [comment]
Oh! I fix it, after Restart! I do not know how it was happen, but I know I do it several times.
Thanks man.

**Comment by Max-Enrik** [comment]
Oh! I fix it, after Restart! I do not know how it was happen, but I know I do it several times.
Thanks man.
