### ISSUE TITLE
No `disable table mode` option exists

### ISSUE THREAD

**Issue by non-descriptive** [randy3k/AlignTab#74]
There's no normal way to disable Table mode if it was enabled. Only way for now - try to turn it on with invalid alignment regex. I think it should extra menu option for it.

**Comment by randy3k** [comment]
Esc should exit table mode unless another package has override it.

**Comment by non-descriptive** [comment]
Aren't it should be more explicit? It's not even documented. Plus possible `Esc` override possibility. Probably it's connected to #62 issue about Vintage Mode

**Comment by randy3k** [comment]
Um, i agree that some docs would be helpful. Sre you using vintage mode? You might need to remap the keybinds if necessary.

**Comment by tomhundt-navera** [comment]
Aha, thanks for the info that Esc should exit it.  I could never figure out how it was supposed to work.  I've got the Sublemacs plugin, which does things with Esc and probably caused the issue.

Putting your original mapping at the end of my keymap file fixes it:
```
    // Exit AlignTab "Table Mode" (this binding gets lost somewhere)
    // https://github.com/randy3k/AlignTab/blob/master/Default.sublime-keymap
    {
        "keys": ["escape"], "command": "align_tab_clear_mode",
        "context":
        [
            { "key": "setting.AlignTabTableMode", "operator": "equal", "operand": true }
        ]
    },
```

**Comment by randy3k** [comment]
It seems that it has been overrideded by other package.

**Comment by randy3k** [comment]
Added a command `AlignTab: Exit Table Mode` in case the escape key is stolen by other packages.
