### ISSUE TITLE
Unable to Save

### ISSUE THREAD

**Issue by pattulus** [randy3k/AlignTab#77]
I wanted to add a new pattern - my first custom one - to the context menu:

```json
[
   {"caption" : "-"},
    {
      "id": "aligntab",
      "caption": "AlignTab",
      "children": [
          {
          "caption" : "JSON",
          "command" : "align_tab",
          "args"    : {"user_input" : "(?<=:)\\s{1}/f"}
          }
      ]
  }
]
```

But received a warning that the path didn't exist:

~~`![unable-to-save](https://user-images.githubusercontent.com/591759/37200304-a79ffa18-2384-11e8-8e43-35134e961ac3.png)`~~

I guess AlignTab somehow failed to create the path. I'm on a Mac, maybe that's why the script failed. 

Easy to fix though:

```bash
$ mkdir -p "$HOME/Library/Application Support/Sublime Text 3/Packages/User/AlignTab/"
$ touch "$HOME/Library/Application Support/Sublime Text 3/Packages/User/AlignTab/Context.sublime-menu"
```

---

For those who search the issues, I'll add the plain text of the error here:

    Unable to save ~/Library/Application Support/Sublime Text 3/Packages/User/AlignTab/Context.sublime-menu
    Error: No such file or directory

**Comment by randy3k** [comment]
This's strange. The error message shown seems to be irrelevant to AlignTab.

**Comment by pattulus** [comment]
@randy3k Yes, please ignore the screen shot. I will delete it, I uploaded the wrong one and trashed the AlignTab one. There's a plain text copy of the screen shot at the bottom of my post.

**Comment by randy3k** [comment]
Oic, it must be because the directory didn’t exist.

**Comment by randy3k** [comment]
Fixed. Thanks for the report.
