### ISSUE TITLE
Do not spawn the Table Mode Across new new lines

### ISSUE THREAD

**Issue by evandrocoan** [randy3k/AlignTab#80]
For example:

![back3](https://user-images.githubusercontent.com/5332158/37571784-1b06a774-2ae0-11e8-9e61-e7220236a98d.gif)

It keeps repeatedly aligning with the other pipe `|` several lines below it. It should stop after new empty lines are found, and only align with the lines on its current block, i.e., lines which are together and not separated by new lines.

```
a) L(G) = { a^n b^m| n, m ≥ 0 ∧ n ≠ m}

S  -> AI BP         | AP BI                        | A | B | #epsilon
A  -> a             | a A
B  -> b             | b B
AI -> a             | aa AI
BI -> b             | bb BI
AP -> aa            | aa AP
BP -> bb            | bb BP


b) L(G) = { a^n b^m | n, m ≥ 0 ∧ n + m seja ímpar}

A  -> a     | a A
B  -> b     | b B
AI -> a     | aa AI
BI -> b     | bb BI
AP -> aa    | aa AP
BP -> bb    | bb BP
```

**Comment by randy3k** [comment]
It is by design. If you enter table mode and edit several blocks without leaving the model. The blocks will be aligned at the same time. To resolve your issue, you have to exit the table mode after editing the first mode; reenter the table mode before editing the second mode.

**Comment by evandrocoan** [comment]
Thanks
