### ISSUE TITLE
Replace Input by InputHandler

### ISSUE THREAD

**Issue by deathaxe** [randy3k/AlignTab#82]
The latest release of ST supports InputHandlers to pass arguments to commands.

How about using a ListInputHandler in `align_tab` command to directly list the _history_ and the _named patterns_? This way the align pattern could directly be entered in the Command Palette with all the most important/recent ones by hand.

The currently used `view.show_input()` to enter the pattern could either be removed or used for backward compatibility if InputHandlers are not supported.

**Comment by randy3k** [comment]
sounds like a good idea. With that said, I don’t think i am going to spend time to this one. (to be honest, I hv never read the doc for InputHandler and have never known how it works)

**Comment by deathaxe** [comment]
Seems not to be too difficult. Already played around with it a bit. Maybe prepare a PR.

**Comment by randy3k** [comment]
one potential problem though is that the InputHandler may block the view when the preview mode is on.

**Comment by deathaxe** [comment]
You mean it hides the part of the content, which is to be aligned?

**Comment by randy3k** [comment]
Ya, it’s what I meant.

**Comment by deathaxe** [comment]
Even though the InputHandlers can improve the workflow, the disadvantage of hiding the view partly causes them to not being suitable for that use case.
